### ISSUE TITLE
locator pallet

### ISSUE THREAD

**Issue by steveoh** [agrc/warehouse#33]
Is this pallet is working?

![image](https://cloud.githubusercontent.com/assets/325813/19936549/6981bb42-a0e3-11e6-9af9-3c38d4885fe5.png)

~~Should the [sddrafts folder](https://github.com/agrc/warehouse/blob/master/mapserv/LocatorsPallet.py#L48) be published to github?~~

It appears to be a forgotten secret. I updated the readme and added the missing items.

If I am reading this pallet correctly, the locators need to be in the `locators.gdb` prior to a run. This is problematic for a few reasons. We should be able to purge the staging data and have things rebuild properly. 

A corrupt locator has no way to recover without intervention. 

> Failed to execute. Parameters are not valid. ERROR 000732: Input Address Locator: Dataset staging\locators.gdb\AddressPoints_AddressSystem does not exist or is not supported Failed to execute (RebuildAddressLocator).

Keeping a gdb of valid locators with the project in github could give us the opportunity to generate the locators.gdb by `arcpy.copy_management`. We could update the data, (delete if exists) copy the valid locator into staging, rebuild, and finally publish. 

Thoughts?

**Comment by stdavis** [comment]
I don't think that we can assume that everything in staging is reproducible. There are some datasets that are static that are maintained there. Although I agree that this would be ideal.

I wonder if the copy method would work reliably. I've had varied success copying address locators.

**Comment by steveoh** [comment]
> There are some datasets that are static that are maintained there.

This was not be the intention of the staging area as staging should not become another MapData mess. We should be able to add and remove pallets, delete the staging area and only have what is necessary be there. There needs to be another solution to the static problem.

**Comment by stdavis** [comment]
> We should be able to add and remove pallets, delete the staging area and only have what is necessary be there.

That would break some production services if we removed multiple pallets that participated in updating the same fgdb.

I can see where you are coming from. I'd be open to other solutions for static data.

**Comment by steveoh** [comment]
The use case would more so be that we retire an application than run a subset of necessary pallets. 

Will you open another ticket with the static data you are aware of and how it's being managed in staging?

**Comment by steveoh** [comment]
So, [the best practice for creating locators](http://desktop.arcgis.com/en/arcmap/latest/manage-data/geocoding/creating-an-address-locator.htm), for more performance etc, is to store them on the file system like a toolbox - outside of a geodatabase. We should consider this change for an upcoming 10.5 update and for the performance and possible stability issue was currently have.
