### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by steveoh** [agrc/warehouse#6]
Hey @MichaelAGRC, [userDataList](https://github.com/agrc/warehouse/blob/master/database_maintenance/UTRANS/utrans.py#L59) is not used. Is this a bug or should it be removed?

**Comment by stdavis** [comment]
Same with `userName` and `current_folder`.

**Comment by steveoh** [comment]
i'm pretty sure `current_folder` is in the template @stdavis. And yes, `userName` will be unused if `userDataList` is unused.

**Comment by stdavis** [comment]
Yes, `current_folder` can be removed from the template if you are going to stick the connection files in the garage.

**Comment by steveoh** [comment]
i fixed this in a pull request that is coming.
